version: '3'

services:
  moberries-api:
    build: .
    image: moberries/api
    command: >
      bash -c 'yarn install && yarn db:migrate && yarn db:seed:all && yarn dev'
    volumes:
      - './src:/usr/src/app/src'
      - './.env:/usr/src/app/.env'
      - './package.json:/usr/src/app/package.json'
      - "moberries-node_modules:/usr/src/app/node_modules"
    ports:
      - '9000:8080'
    environment:
      SERVER_OPEN_SWAGGER: "true"
      DATABASE_HOST: "moberries-postgres"
      DATABASE_NAME: "moberries"
      DATABASE_USERNAME: "api"
      DATABASE_PASSWORD: "api"
      NODE_ENV: "development"
    depends_on: 
      - moberries-postgres
    networks:
      - moberries
  moberries-postgres:
    image: postgres:9.6
    volumes:
      - "moberries-postgres-db:/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    environment:
      PGDATA: "/var/lib/postgresql/data/pgdata"
      POSTGRES_USER: "api"
      POSTGRES_PASSWORD: "api"
      POSTGRES_DB: "moberries"
    networks:
      - moberries
  unit-test:
    build: .
    image: moberries/api-test
    command: yarn unit-test
    volumes:
      - './src:/usr/src/app/src'
      - './.env:/usr/src/app/.env'
      - './__tests__:/usr/src/app/__tests__'
    networks:
      - moberries
volumes:
  moberries-postgres-db:
  moberries-node_modules:
networks:
  moberries:
